<?php

namespace ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return user
     */
    public function findFirst(){
        $qb= $this->getQueryBuilder()->orderBy('a.id','asc')->setMaxResults(1);
        return $qb->getQuery()->getSingleResult();
    }
    private function getQueryBuilder(){
        $em = $this->getEntityManager();
        $qb=$em->getRepository('ModelBundle:User')->createQueryBuilder('u');
        return $qb;
    }
}
